
services:
  ml-service:
    container_name: ml-service
    build:
      context: .
      dockerfile: ml-service/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - ./ml-service/src:/app/src
      - ./data:/app/data
    restart: unless-stopped

  db-service:
    container_name: db-service
    build:
      context: .
      dockerfile: db-service/Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./access_key.txt
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - ./db-service/src:/app/src
    restart: unless-stopped
    
  data-service:
    container_name: data-service
    build:
      context: .
      dockerfile: data-service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - ./data-service/src:/app/src
      - ./data:/app/data
    restart: unless-stopped

  scheduler-service:
    build:
      context: .
      dockerfile: scheduler-service/Dockerfile
    container_name: scheduler-service
    depends_on:
      - data-service
    restart: unless-stopped