
services:
  ml-service:
    container_name: ml-service
    build:
      context: .
      dockerfile: ml-service/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - ./ml-service/src:/app/src
      - ./data:/app/data
    restart: unless-stopped

  backend-service:
    container_name: backend-service
    build:
      context: .
      dockerfile: backend-service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - ./backend-service/src:/app/src
    restart: unless-stopped